[package]
name = "advent-of-code-2018"
version = "0.0.0"
license = "MIT"
repository = "https://github.com/mehcode/advent-of-code-2018"
edition = "2018"
authors = [
    "Ryan Leckey <leckey.ryan@gmail.com>"
]

[dependencies]
failure = "0.1.3"
itertools = "0.7.11"
maplit = "1.0.1"
